### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by makkrnic** [kperanovic/chat-app#1]
It doesn't compile:

```
# github.com/Sartura/common/lib/cid
../../common/lib/cid/cid.go:20:19: multiple-value uuid.NewV4() in single-value context
```

**Comment by kperanovic** [comment]
This is a package specific error, could you please send the command you executed so I can replicate the problem?

**Comment by makkrnic** [comment]
This was my mistake. I forgot to run `dep`
